CREATE DATABASE SUPERMERCADO;
USE SUPERMERCADO;

CREATE TABLE CATEGORIA
(
ID smallint not null primary key,
NOMBRE VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCTO
(
CODIGO INTEGER NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(40) NOT NULL,
PRECIO FLOAT NOT NULL,
IDCATEGORIA smallint NOT NULL,
foreign key (IDCATEGORIA) references CATEGORIA(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);

SELECT *
FROM CATEGORIA;
INSERT INTO CATEGORIA VALUES (1, 'GASEOSAS');
INSERT INTO CATEGORIA VALUES (2, 'CARNE');
INSERT INTO CATEGORIA VALUES (3, 'ENERGIZANTES');
INSERT INTO CATEGORIA VALUES (4, 'ABARROTES');


SELECT *
FROM PRODUCTO;
INSERT INTO PRODUCTO VALUES (1001, 'cocacola 2lts', '10', 1) ;
INSERT INTO PRODUCTO VALUES (1002, 'cocacola 3lts', '15', 1);
INSERT INTO PRODUCTO VALUES (1003, 'Arroz 1kg', '7', 4);
INSERT INTO PRODUCTO VALUES (1004, 'carne de res', '10', 2);
INSERT INTO PRODUCTO VALUES (1005, 'Red Bull 1lt', '10', 3);
INSERT INTO PRODUCTO VALUES (1006, 'Azucar 1g', '10', 4);
INSERT INTO PRODUCTO VALUES (1007, 'Fanta de 2lts', '10', 1);

/* SI ID=1 CAMBIA A 5 /
UPDATE CATEGORIA
SET ID=5
WHERE ID=1;

/ELIMINA TODA LA CATEGORIA GASEOSA/
DELETE FROM CATEGORIA
WHERE NOMBRE = 'GASEOSAS';

/MOSTRAR TODOS LOS ´PRODUCTOS DE LA CATEGORIA ES UNO/
SELECT
FROM PRODUCTO
WHERE IDCATEGORIA = 1;

/MOSTRAR TODOS LOS ´PRODUCTOS DE LA CATEGORIA ES GASEOSAS/
SELECT CODIGO, PRODUCTO.NOMBRE, PRECIO
FROM PRODUCTO, CATEGORIA -- (UNION NATURAL, USO DE DOS TABLAS RELACIONADAS)
WHERE IDCATEGORIA = ID AND CATEGORIA.NOMBRE = 'GASEOSAS';


/MOSTRAR TODOS LOS ´PRODUCTOS DE LA CATEGORIA ES GASEOSAS CON PRECIO DE 10 BS/
SELECT CODIGO, PRODUCTO.NOMBRE, PRECIO
FROM PRODUCTO, CATEGORIA -- (UNION NATURAL, USO DE DOS TABLAS RELACIONADAS)
WHERE IDCATEGORIA = ID AND CATEGORIA.NOMBRE = 'GASEOSAS' AND PRECIO = 10;